language: node_js
node_js:
- 0.10
sudo: false
before_install:
- gem install compass
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g bower grunt-cli
- bower install -f
script:
- npm test
- grunt build
env:
- CI_ENV=1
before_deploy:
- git config --global user.email 'bot@travis-ci.com'
- git config --global user.name 'Bot - Travis CI'
- git checkout $TRAVIS_BRANCH
- tar cvzf dist.tar.gz dist/
- git add -f dist.tar.gz
- git commit -am 'Travis Deployment'
deploy:
  provider: openshift
  user: riggerthegeek
  password:
    secure: HYtdzirx98bU/iIfj9bRS7n7LOiyh/Ksd8cKSTbwmgCLo42tr7/uAEXdHCz1ylQE3WumiT1S1ta2NHK8Fzr+YzikXqc10JNj4TvjzlHsr1+p4ZEFgLFeMkTWqFa5tvReaXfT51KEC9hfl2EuCSq0QZD6MEerZcbTqgUnmfrVab0=
  app: kitbagweb
  domain: riggerthegeek
  on:
    repo: slash-dev-slash-null/kitbag-web
  skip_cleanup: true
